# Generated by Django 3.0.3 on 2020-03-10 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YogaPose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(blank=True, max_length=150, null=True)),
                ('sanskrit_name', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(upload_to='static/img/yogaposes')),
                ('video', models.CharField(blank=True, max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yoga Pose',
                'verbose_name_plural': 'Yoga Poses',
                'ordering': ['sanskrit_name', 'english_name'],
            },
        ),
        migrations.CreateModel(
            name='YogaPoseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True, null=True)),
                ('yogapose', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yogapose', to='yogaposes.YogaPose')),
            ],
        ),
    ]
