# Generated by Django 3.0.3 on 2020-03-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaposes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogapose',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='YogaPoseInfo',
        ),
    ]
