# Generated by Django 3.0.3 on 2020-03-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0002_auto_20200310_1300'),
        ('yogaposes', '0002_auto_20200310_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogapose',
            name='contraindicated_conditions',
            field=models.ManyToManyField(to='conditions.Condition'),
        ),
    ]
