# Generated by Django 3.0.3 on 2020-03-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaposes', '0003_yogapose_contraindicated_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogapose',
            name='english_name',
            field=models.CharField(blank=True, default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yogapose',
            name='sanskrit_name',
            field=models.CharField(blank=True, default='', max_length=150),
            preserve_default=False,
        ),
    ]
