# Generated by Django 3.0.3 on 2020-03-13 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0002_auto_20200310_1300'),
        ('yogaposes', '0004_auto_20200312_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficialPoses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why_these_poses_help', models.TextField(blank=True, null=True)),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='static/img/beneficial_poses')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='static/img/beneficial_poses')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='static/img/beneficial_poses')),
                ('video', models.CharField(blank=True, max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('condition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='conditions.Condition')),
                ('image_dropdown', models.ManyToManyField(blank=True, default=None, related_name='beneficial_poses_images', to='yogaposes.YogaPose')),
                ('poses', models.ManyToManyField(blank=True, default=None, null=True, related_name='beneficial_poses', to='yogaposes.YogaPose')),
            ],
            options={
                'verbose_name': 'Beneficial Poses and Explanations',
                'verbose_name_plural': 'Beneficial Poses and Explanations',
            },
        ),
    ]
