# Generated by Django 3.0.3 on 2020-03-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaposes', '0005_beneficialposes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficialposes',
            name='poses',
            field=models.ManyToManyField(blank=True, default=None, related_name='beneficial_poses', to='yogaposes.YogaPose'),
        ),
    ]
