# Generated by Django 3.0.3 on 2020-12-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaposes', '0006_auto_20200313_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficialposes',
            name='video_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
