# Generated by Django 3.0.3 on 2020-03-10 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conditioncategory',
            old_name='notes',
            new_name='description',
        ),
    ]
