# Generated by Django 3.0.3 on 2020-03-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0002_auto_20200310_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditioncategory',
            name='special_case',
            field=models.BooleanField(default=False),
        ),
    ]
