# Generated by Django 3.0.3 on 2020-03-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0003_conditioncategory_special_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditioncategory',
            name='special_case',
        ),
        migrations.AddField(
            model_name='condition',
            name='special_case',
            field=models.BooleanField(default=False),
        ),
    ]
