# Generated by Django 3.0.3 on 2020-12-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0004_auto_20200316_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='special_case',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
