# Generated by Django 3.0.3 on 2020-12-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0005_auto_20201211_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='alternate_name_four',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='alternate_name_one',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='alternate_name_three',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='alternate_name_two',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
