# Generated by Django 3.0.3 on 2020-03-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_auto_20200306_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogastyle',
            name='title',
            field=models.CharField(default='No title', max_length=50),
        ),
    ]
