# Generated by Django 3.0.3 on 2020-03-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_auto_20200310_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchentry',
            name='search_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
