# Generated by Django 3.0.3 on 2020-12-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0004_searchentry_search_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='street',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
