# Generated by Django 3.0.3 on 2020-12-21 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='subscriber_id',
        ),
    ]
