input {
    beats {
        port => 5045
    }
}

filter {
    if ([container][name] == "webapp") {
        mutate {
            replace => {
                "[type]" => "webapp"
            }
        }
        grok {
            match => { "message" => "\[pid: %{NUMBER:pid}\|app: %{NUMBER:id}\|req: %{NUMBER:currentReq}/%{NUMBER:totalReq}\] %{IP:remoteAddress} \(\) \{%{NUMBER:CGIVar} vars in %{NUMBER:CGISize} bytes\} \[%{DATA:timestamp}\] %{WORD:method} %{URIPATHPARAM:uri} \=\> generated %{NUMBER:resSize} bytes in %{NUMBER:resTime} msecs \(HTTP/%{NUMBER:httpVersion} %{NUMBER:status}\) %{NUMBER:headers} headers in %{NUMBER:headersSize} bytes %{GREEDYDATA:coreInfo}" }
        }
        mutate {
            convert => ["status", "integer"]
            convert => ["resSize", "integer"]
            convert => ["resTime", "float"]
        }
    } else if ([container][name] == "nginx") {
        mutate {
            replace => {
                "[type]" => "nginx"
            }
        }
        grok { 
            match => { "message" => "%{IPORHOST:clientip} (?:-|(%{WORD}.%{WORD})) %{USER:ident} \[%{HTTPDATE:timestamp}\] (?:%{WORD:verb} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion})?|%{DATA:rawrequest}) %{NUMBER:response} (?:%{NUMBER:bytes}|-) %{QS:referrer} %{QS:agent} %{QS:forwarder}" }
        }
        geoip {
            source => "clientip"
        }
        if "kibana" in [message] { drop { } }
    } else if ([container][name] == "email_worker") {
        mutate {
            replace => {
                "[type]" => "email_worker"
            }
        }
        grok {
            match => { "message" => "%{GREEDYDATA:message}" }
        }
    } else if ([container][name] == "mailchimp_worker") {
        mutate {
            replace => {
                "[type]" => "mailchimp_worker"
            }
        }
        grok {
            match => { "message" => "%{GREEDYDATA:message}" }
        }
    } else {
        mutate {
            replace => {
                "[type]" => "postgresql"
            }
        }
    }
}

output {
    elasticsearch {
        hosts => ["elasticsearch:9200"]
        index => "%{type}-%{+YYYY.MM.dd}"
    }
    stdout { codec => rubydebug }
}
